### ISSUE TITLE
Useless use of getppid in void context at Makefile.PL line 42

### ISSUE THREAD

**Issue by ballapete** [uperl/Shell-Guess#12]
Hello!

This message is reported by Perl 5.34 on a Mac with macOS 10.13.6/darwin17.7.0. What should the line look like?

**Comment by plicease** [comment]
I'm guessing it is this:

`eval { getppid; 1 }`

in this case we are just checking if calling `getppid` throws an exception, so it isn't actually useless :) however, we can probably suppress the warning if we change it to:

`eval { my $pid = getppid; 1 }`

Thank you for reporting this, extraneous warnings always feel so untidy to me.

**Comment by ballapete** [comment]
> Am 03.12.2024 um 16:23 schrieb Graham✈️✈️ ***@***.***>:
> 
> Thank you for reporting this, extraneous warnings always feel so untidy to me.

We have one thing in common!


And YES: this change removes the complaint. (I have saved a patch so that MacPorts users will not see the useless complaint.)

--

Greetings

  Pete

Don't force it; get a larger hammer. 
– Anthony's Law of Force

**Comment by plicease** [comment]
fixed in #13 released as `0.10`
